name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas openpyxl

    - name: Build do Executável
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=android-icon-192x192.ico matriz_priorizacao.py

    - name: Upload do Executável
      uses: actions/upload-artifact@v4
      with:
        name: matriz_priorizacao_windows
        path: dist/matriz_priorizacao.exe

